apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/example1/nginx-example@sha256:90e1befdddda55f2c7396ecb0fe5e5babfa8a00f22abe9601f1d1985541cf22e
        name: nginx-example
        ports:
        - containerPort: 8080
