apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/example1/nginx-example:latest
        name: nginx-example
        ports:
        - containerPort: 8080
