apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nginx-example
  namespace: example1
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nginx-example:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/sclorg/nginx-ex.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nginx:1.18-ubi8'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/nginx@sha256:e9871d900f62897102ac8008c8392d8d76cc6862ee5bda14234d73cdb6da200a
      type: ImageChange
    - type: ConfigChange
