apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example2
  namespace: example2
spec:
  destination:
    namespace: example2
    server: 'https://kubernetes.default.svc'
  project: example2
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: .
    repoURL: 'git@github.com:kamkie/argocd-examples2.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
